# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rubyzip/all/rubyzip.rbi
#
# rubyzip-3.4.1

module Zip
  extend Zip
end
class Zip::DOSTime < Time
  include Zip::DOSTime::JRubyCMP
end
module Zip::DOSTime::JRubyCMP
end
module Zip::IOExtras
end
module Zip::IOExtras::AbstractInputStream
  include Enumerable
  include Zip::IOExtras::FakeIO
end
module Zip::IOExtras::AbstractOutputStream
  include Zip::IOExtras::FakeIO
end
module Zip::IOExtras::FakeIO
end
module Zip::Dirtyable
end
module Zip::Dirtyable::ClassMethods
end
class Zip::Entry
  extend Zip::Dirtyable::ClassMethods
  include Zip::Dirtyable
end
class Zip::ExtraField::Generic
end
class Zip::ExtraField::Unknown < Zip::ExtraField::Generic
end
class Zip::ExtraField::UniversalTime < Zip::ExtraField::Generic
end
class Zip::ExtraField::OldUnix < Zip::ExtraField::Generic
end
class Zip::ExtraField::IUnix < Zip::ExtraField::Generic
end
class Zip::ExtraField::Zip64 < Zip::ExtraField::Generic
end
class Zip::ExtraField::NTFS < Zip::ExtraField::Generic
end
class Zip::ExtraField::AES < Zip::ExtraField::Generic
end
class Zip::ExtraField < Hash
end
class Zip::EntrySet
  include Enumerable
end
class Zip::CentralDirectory
  extend Forwardable
  extend Zip::Dirtyable::ClassMethods
  include Zip::Dirtyable
end
module Zip::FileSplit
end
class Zip::File
  extend Forwardable
  extend Zip::FileSplit
  include Enumerable
  include Zip::FileSystem
end
class Zip::InputStream
  include Zip::IOExtras::AbstractInputStream
end
class Zip::OutputStream
  extend Forwardable
  include Zip::IOExtras::AbstractOutputStream
end
class Zip::Decompressor
end
class Zip::Compressor
end
module Zip::NullDecompressor
end
class Zip::NullCompressor < Zip::Compressor
  extend Singleton::SingletonClassMethods
  include Singleton
end
module Zip::NullInputStream
  include Zip::IOExtras::AbstractInputStream
  include Zip::NullDecompressor
end
class Zip::PassThruCompressor < Zip::Compressor
end
class Zip::PassThruDecompressor < Zip::Decompressor
end
class Zip::DecryptedIo
end
class Zip::Encrypter
end
class Zip::Decrypter
end
module Zip::NullEncryption
end
class Zip::NullEncrypter < Zip::Encrypter
  include Zip::NullEncryption
end
module Zip::TraditionalEncryption
end
class Zip::TraditionalEncrypter < Zip::Encrypter
  include Zip::TraditionalEncryption
end
class Zip::TraditionalDecrypter < Zip::Decrypter
  include Zip::TraditionalEncryption
end
module Zip::AESEncryption
end
class Zip::AESDecrypter < Zip::Decrypter
  include Zip::AESEncryption
end
class Zip::Inflater < Zip::Decompressor
end
class Zip::Deflater < Zip::Compressor
end
class Zip::StreamableStream < Anonymous_Delegator_58
end
class Zip::StreamableDirectory < Zip::Entry
end
class Zip::Error < StandardError
end
class Zip::CompressionMethodError < Zip::Error
end
class Zip::DecompressionError < Zip::Error
end
class Zip::DestinationExistsError < Zip::Error
end
class Zip::EntryExistsError < Zip::Error
end
class Zip::EntryNameError < Zip::Error
end
class Zip::EntrySizeError < Zip::Error
end
class Zip::EntryNumberMismatchError < Zip::Error
end
class Zip::SplitArchiveError < Zip::Error
end
class Zip::StreamingError < Zip::Error
end
module Zip::FileSystem
end
class Zip::FileSystem::ZipFileNameMapper
  include Enumerable
end
class Zip::FileSystem::DirectoryIterator
  include Enumerable
end
class Zip::FileSystem::Dir
end
class Zip::FileSystem::File
end
class Zip::FileSystem::File::Stat
end
