AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'storage/**/*'
    - 'public/**/*'
    - 'coverage/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'

# Отключить сложные проверки
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  Enabled: false